---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    vector_version: "0.42.0"
    vector_sources_extra:
      internal_metrics:
        type: internal_metrics
    vector_sinks:
      console:
        type: console
        inputs:
          - internal_metrics
        encoding:
          codec: json

  roles:
    - role: jackson.vector
