---
- name: Restart vector
  ansible.builtin.systemd:
    name: "{{ vector_service_name }}"
    state: restarted
    daemon_reload: true
  when: vector_service_state != 'stopped'

- name: Reload vector
  ansible.builtin.systemd:
    name: "{{ vector_service_name }}"
    state: reloaded
  when: vector_service_state != 'stopped'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
