---
- name: Configure /etc/krb.conf
  ansible.builtin.template:
    src: krb.conf.j2
    dest: /etc/krb.conf
    owner: root
    group: root
    mode: "0644"
  when: base_server_krb_realm | length > 0
