---
- name: Configure HTTP proxy environment
  ansible.builtin.include_tasks:
    file: proxy_env.yml
  tags:
    - base_server
    - base_server_proxy

- name: Configure CA certificate
  ansible.builtin.include_tasks:
    file: ca_cert.yml
  tags:
    - base_server
    - base_server_ca_cert

- name: Flush handlers to update CA trust immediately
  ansible.builtin.meta: flush_handlers
  tags:
    - base_server
    - base_server_ca_cert

- name: Configure Docker daemon proxy
  ansible.builtin.include_tasks:
    file: docker_proxy.yml
  tags:
    - base_server
    - base_server_docker_proxy

- name: Configure VAS
  ansible.builtin.include_tasks:
    file: vas.yml
  tags:
    - base_server
    - base_server_vas

- name: Configure CIFS mount
  ansible.builtin.include_tasks:
    file: cifs.yml
  tags:
    - base_server
    - base_server_cifs

- name: Configure Kerberos
  ansible.builtin.include_tasks:
    file: krb.yml
  tags:
    - base_server
    - base_server_krb
