---
- name: Install vasd SELinux policy dependencies
  ansible.builtin.dnf:
    name:
      - policycoreutils-python-utils
      - policycoreutils
      - selinux-policy-devel
    state: present
  when: base_server_vas_realm | length > 0

- name: Check if vasd SELinux policy is installed
  ansible.builtin.command:
    cmd: semodule -l
  register: _vas_selinux_modules
  changed_when: false
  when: base_server_vas_realm | length > 0

- name: Configure vasd SELinux policy
  ansible.builtin.command:
    cmd: /opt/quest/bin/vastool configure selinux
  when:
    - base_server_vas_realm | length > 0
    - "'vasd' not in _vas_selinux_modules.stdout"

- name: Ensure VAS configuration directory exists
  ansible.builtin.file:
    path: /etc/opt/quest/vas
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: base_server_vas_realm | length > 0

- name: Configure vas.conf
  ansible.builtin.template:
    src: vas.conf.j2
    dest: /etc/opt/quest/vas/vas.conf
    owner: root
    group: root
    mode: "0644"
  when: base_server_vas_realm | length > 0

- name: Configure users.allow
  ansible.builtin.copy:
    content: "# Do not edit directly. Managed by Ansible\n{{ base_server_vas_users_allow }}"
    dest: /etc/opt/quest/vas/users.allow
    owner: root
    group: root
    mode: "0644"
  when: base_server_vas_users_allow | length > 0
