---
base_server_http_proxy: ""
base_server_https_proxy: "{{ base_server_http_proxy }}"
base_server_no_proxy: ""

base_server_ca_cert_url: ""
base_server_ca_cert_filename: "custom-ca.crt"

base_server_cifs_share: ""
base_server_cifs_mount_point: "/mnt/share"
base_server_cifs_username: ""
base_server_cifs_password: ""
base_server_cifs_domain: ""
base_server_cifs_options: "vers=3.0,uid=0,gid=0,file_mode=0644,dir_mode=0755"

base_server_vas_realm: ""
base_server_vas_users_allow: ""

base_server_krb_realm: "{{ base_server_vas_realm }}"
