---
galaxy_info:
  role_name: windows_exporter
  namespace: jackson
  author: Jackson
  description: Install and configure Prometheus windows_exporter on Windows hosts
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - monitoring
    - prometheus
    - windows
    - exporter
    - metrics

dependencies: []
